# Generated by Django 3.2.23 on 2023-11-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbycentre', '0002_auto_20231129_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
