# Generated by Django 3.2.23 on 2023-11-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbycentre', '0003_auto_20231130_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
