# Generated by Django 3.2.23 on 2023-11-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbycentre', '0005_auto_20231130_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, to='hobbycentre.Category'),
        ),
    ]
